=== kwoqer/ocons/trunk/ocons/db/local.dtd
<!ELEMENT Localization (locallist)>
<!ATTLIST Localization lang CDATA #REQUIRED>
<!ELEMENT locallist (G_Language,G_Attention,G_Error,G_Open,G_Save,G_Cancel,G_Yes,G_No,G_Ok,G_AYouSure,ACD_Title,ACD_PersonalNumber,ACD_Name,ACD_Phone,ACD_EMail,ACD_Remember,ACD_Password,ACD_RepeatPassword,ACD_RedLighting,ACD_ConsultantPresent,ACD_PasswordsNotCoincide,LD_Title,LD_Number,LD_Password,LD_Enter,LD_ConsultantNumberNotPoint,LD_IncorrectPassword,LD_ConsultantNumberNotFound,MM_1_Control,MM_Config,MM_AboutProgram,MM_Exit,MM_2_Consultant,MM_NewConsultant,MM_Enter,MM_OtherConsultant,MM_ConfirmOtherConsultant,NT_Clients,NT_Invoices,NT_Catalogs,NT_Pricelist,NT_Reports,NT_Orders,NT_Contacts,IP_Clients,IP_Catalogs,IP_Orders,IP_Invoices,IP_Prices,IP_AddAction,IP_DeleteAction,IP_EditAction,IP_FindAction,IP_PreviewAction,IP_PrintAction,IP_CatalogNumber,IP_CatalogGiveDate,IP_CatalogReturnDate,IP_CatalogReturned,IP_CatalogInfo,IP_ClientName,IP_ClientPhone,IP_ClientPhoneMob,IP_ClientAdress,IP_ClientBirthday,IP_ClientOther,IP_ClientOtherDate,IP_ClientStatus,IP_ClientStatus_1,IP_ClientStatus_2,IP_ClientDiscount,IP_ClientIncorrectDiscountFormat,IP_ClientAdd,IP_ClientEdit,IP_OrderDate,IP_OrderQuantity,IP_InvoicesID,IP_InvoicesOrdered,IP_InvoicesReceived,IP_InvoicesPrice,IP_InvoicesPoints,IP_ProductID,IP_ProductGetDate,IP_ProductGetPrice,IP_ProductRealDate,IP_ProductRealPrice,IP_EventsComing,IP_EventsCompletion,IP_EventsFixed,IP_EventInfo,IP_Contact,IP_ContactPhone,IP_ContactWhereFind,IP_ContactWhereFind_1,IP_ContactWhereFind_2,IP_ContactWhereFind_3,IP_ContactWhereFind_4,IP_ContactName,IP_ContactDate,IP_ContactStatus)>
<!ELEMENT G_Language (#PCDATA)>
<!ELEMENT G_Attention (#PCDATA)>
<!ELEMENT G_Error (#PCDATA)>
<!ELEMENT G_Open (#PCDATA)>
<!ELEMENT G_Save (#PCDATA)>
<!ELEMENT G_Cancel (#PCDATA)>
<!ELEMENT G_Yes (#PCDATA)>
<!ELEMENT G_No (#PCDATA)>
<!ELEMENT G_Ok (#PCDATA)>
<!ELEMENT G_AYouSure (#PCDATA)>
<!ELEMENT ACD_Title (#PCDATA)>
<!ELEMENT ACD_PersonalNumber (#PCDATA)>
<!ELEMENT ACD_Name (#PCDATA)>
<!ELEMENT ACD_Phone (#PCDATA)>
<!ELEMENT ACD_EMail (#PCDATA)>
<!ELEMENT ACD_Remember (#PCDATA)>
<!ELEMENT ACD_Password (#PCDATA)>
<!ELEMENT ACD_RepeatPassword (#PCDATA)>
<!ELEMENT ACD_RedLighting (#PCDATA)>
<!ELEMENT ACD_ConsultantPresent (#PCDATA)>
<!ELEMENT ACD_PasswordsNotCoincide (#PCDATA)>
<!ELEMENT LD_Title (#PCDATA)>
<!ELEMENT LD_Number (#PCDATA)>
<!ELEMENT LD_Password (#PCDATA)>
<!ELEMENT LD_Enter (#PCDATA)>
<!ELEMENT LD_ConsultantNumberNotPoint (#PCDATA)>
<!ELEMENT LD_IncorrectPassword (#PCDATA)>
<!ELEMENT LD_ConsultantNumberNotFound (#PCDATA)>
<!ELEMENT MM_1_Control (#PCDATA)>
<!ELEMENT MM_Config (#PCDATA)>
<!ELEMENT MM_AboutProgram (#PCDATA)>
<!ELEMENT MM_Exit (#PCDATA)>
<!ELEMENT MM_2_Consultant (#PCDATA)>
<!ELEMENT MM_NewConsultant (#PCDATA)>
<!ELEMENT MM_Enter (#PCDATA)>
<!ELEMENT MM_OtherConsultant (#PCDATA)>
<!ELEMENT MM_ConfirmOtherConsultant (#PCDATA)>
<!ELEMENT NT_Clients (#PCDATA)>
<!ELEMENT NT_Invoices (#PCDATA)>
<!ELEMENT NT_Catalogs (#PCDATA)>
<!ELEMENT NT_Pricelist (#PCDATA)>
<!ELEMENT NT_Reports (#PCDATA)>
<!ELEMENT NT_Orders (#PCDATA)>
<!ELEMENT NT_Contacts (#PCDATA)>
<!ELEMENT IP_Clients (#PCDATA)>
<!ELEMENT IP_Catalogs (#PCDATA)>
<!ELEMENT IP_Orders (#PCDATA)>
<!ELEMENT IP_Invoices (#PCDATA)>
<!ELEMENT IP_Prices (#PCDATA)>
<!ELEMENT IP_AddAction (#PCDATA)>
<!ELEMENT IP_DeleteAction (#PCDATA)>
<!ELEMENT IP_EditAction (#PCDATA)>
<!ELEMENT IP_FindAction (#PCDATA)>
<!ELEMENT IP_PreviewAction (#PCDATA)>
<!ELEMENT IP_PrintAction (#PCDATA)>
<!ELEMENT IP_CatalogNumber (#PCDATA)>
<!ELEMENT IP_CatalogGiveDate (#PCDATA)>
<!ELEMENT IP_CatalogReturnDate (#PCDATA)>
<!ELEMENT IP_CatalogReturned (#PCDATA)>
<!ELEMENT IP_CatalogInfo (#PCDATA)>
<!ELEMENT IP_ClientName (#PCDATA)>
<!ELEMENT IP_ClientPhone (#PCDATA)>
<!ELEMENT IP_ClientPhoneMob (#PCDATA)>
<!ELEMENT IP_ClientAdress (#PCDATA)>
<!ELEMENT IP_ClientBirthday (#PCDATA)>
<!ELEMENT IP_ClientOther (#PCDATA)>
<!ELEMENT IP_ClientOtherDate (#PCDATA)>
<!ELEMENT IP_ClientStatus (#PCDATA)>
<!ELEMENT IP_ClientStatus_1 (#PCDATA)>
<!ELEMENT IP_ClientStatus_2 (#PCDATA)>
<!ELEMENT IP_ClientDiscount (#PCDATA)>
<!ELEMENT IP_ClientIncorrectDiscountFormat (#PCDATA)>
<!ELEMENT IP_ClientAdd (#PCDATA)>
<!ELEMENT IP_ClientEdit (#PCDATA)>
<!ELEMENT IP_OrderDate (#PCDATA)>
<!ELEMENT IP_OrderQuantity (#PCDATA)>
<!ELEMENT IP_InvoicesID (#PCDATA)>
<!ELEMENT IP_InvoicesOrdered (#PCDATA)>
<!ELEMENT IP_InvoicesReceived (#PCDATA)>
<!ELEMENT IP_InvoicesPrice (#PCDATA)>
<!ELEMENT IP_InvoicesPoints (#PCDATA)>
<!ELEMENT IP_ProductID (#PCDATA)>
<!ELEMENT IP_ProductGetDate (#PCDATA)>
<!ELEMENT IP_ProductGetPrice (#PCDATA)>
<!ELEMENT IP_ProductRealDate (#PCDATA)>
<!ELEMENT IP_ProductRealPrice (#PCDATA)>
<!ELEMENT IP_EventsComing (#PCDATA)>
<!ELEMENT IP_EventsCompletion (#PCDATA)>
<!ELEMENT IP_EventsFixed (#PCDATA)>
<!ELEMENT IP_EventInfo (#PCDATA)>
<!ELEMENT IP_Contact (#PCDATA)>
<!ELEMENT IP_ContactPhone (#PCDATA)>
<!ELEMENT IP_ContactWhereFind (#PCDATA)>
<!ELEMENT IP_ContactWhereFind_1 (#PCDATA)>
<!ELEMENT IP_ContactWhereFind_2 (#PCDATA)>
<!ELEMENT IP_ContactWhereFind_3 (#PCDATA)>
<!ELEMENT IP_ContactWhereFind_4 (#PCDATA)>
<!ELEMENT IP_ContactName (#PCDATA)>
<!ELEMENT IP_ContactDate (#PCDATA)>
<!ELEMENT IP_ContactStatus (#PCDATA)>

=== kwoqer/ocons/ocons/db/lang_RU.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Localization SYSTEM "local.dtd">
<Localization lang="RU">
    <locallist>
        <G_Language>Язык</G_Language>
        <G_Attention>Внимание!</G_Attention>
        <G_Error>Ошибка!</G_Error>
        <G_Open>Открыть</G_Open>
        <G_Save>Сохранить</G_Save>
        <G_Cancel>Отмена</G_Cancel>
        <G_Yes>Да</G_Yes>
        <G_No>Нет</G_No>
        <G_Ok>Согласен</G_Ok>
        <G_AYouSure>Вы действительно хотите</G_AYouSure>
        <ACD_Title>Новый консультант</ACD_Title>
        <ACD_PersonalNumber>Личный номер</ACD_PersonalNumber>
        <ACD_Name>Фамилия И.О.</ACD_Name>
        <ACD_Phone>Телефон</ACD_Phone>
        <ACD_EMail>E-Mail</ACD_EMail>
        <ACD_Remember>Запомнить меня</ACD_Remember>
        <ACD_Password>Пароль</ACD_Password>
        <ACD_RepeatPassword>Еще раз</ACD_RepeatPassword>
        <ACD_RedLighting>Красным выделены обязательные поля</ACD_RedLighting>
        <ACD_ConsultantPresent>Консультант с таким номером уже есть!</ACD_ConsultantPresent>
        <ACD_PasswordsNotCoincide>Пароли не совпадают!</ACD_PasswordsNotCoincide>
        <LD_Title>Вход</LD_Title>
        <LD_Number>Номер</LD_Number>
        <LD_Password>Пароль</LD_Password>
        <LD_Enter>Вход</LD_Enter>
        <LD_ConsultantNumberNotPoint>Номер консультанта не указан!</LD_ConsultantNumberNotPoint>
        <LD_IncorrectPassword>Неправильный пароль!</LD_IncorrectPassword>
        <LD_ConsultantNumberNotFound>Консультант с таким номером не найден!</LD_ConsultantNumberNotFound>
        <MM_1_Control>Управление</MM_1_Control>
        <MM_Config>Настройки</MM_Config>
        <MM_AboutProgram>О программе</MM_AboutProgram>
        <MM_Exit>Выход</MM_Exit>
        <MM_2_Consultant>Консультант</MM_2_Consultant>
        <MM_NewConsultant>Новый консультант</MM_NewConsultant>
        <MM_Enter>Вход</MM_Enter>
        <MM_OtherConsultant>Другой консультант</MM_OtherConsultant>
        <MM_ConfirmOtherConsultant>Вы действительно хотите зайти другим консультантом?</MM_ConfirmOtherConsultant>
        <NT_Clients>Клиенты</NT_Clients>
        <NT_Invoices>Накладные</NT_Invoices>
        <NT_Catalogs>Каталоги</NT_Catalogs>
        <NT_Pricelist>Прайслист</NT_Pricelist>
        <NT_Reports>Отчеты</NT_Reports>
        <NT_Orders>Заказы</NT_Orders>
        <NT_Contacts>Контакты</NT_Contacts>
        <IP_Clients>клиента</IP_Clients>
        <IP_Catalogs>каталог</IP_Catalogs>
        <IP_Orders>заказ</IP_Orders>
        <IP_Invoices>накладную</IP_Invoices>
        <IP_Prices>прайслист</IP_Prices>
        <IP_AddAction>Добавить</IP_AddAction>
        <IP_DeleteAction>Удалить</IP_DeleteAction>
        <IP_EditAction>Редактировать</IP_EditAction>
        <IP_FindAction>Найти</IP_FindAction>
        <IP_PreviewAction>Просмотреть</IP_PreviewAction>
        <IP_PrintAction>Печатать</IP_PrintAction>
        <IP_CatalogNumber>Номер каталога</IP_CatalogNumber>
        <IP_CatalogGiveDate>Дата выдачи</IP_CatalogGiveDate>
        <IP_CatalogReturnDate>Вернуть</IP_CatalogReturnDate>
        <IP_CatalogReturned>Возвращен</IP_CatalogReturned>
        <IP_CatalogInfo>Примечания</IP_CatalogInfo>
        <IP_ClientName>Ф.И.О. Клиента</IP_ClientName>
        <IP_ClientPhone>Дом. телефон</IP_ClientPhone>
        <IP_ClientPhoneMob>Моб. телефон</IP_ClientPhoneMob>
        <IP_ClientAdress>Адрес</IP_ClientAdress>
        <IP_ClientBirthday>День рождения</IP_ClientBirthday>
        <IP_ClientOther>Иное событие</IP_ClientOther>
        <IP_ClientOtherDate>Дата события</IP_ClientOtherDate>
        <IP_ClientStatus>Статус</IP_ClientStatus>
        <IP_ClientStatus_1>Обычный</IP_ClientStatus_1>
        <IP_ClientStatus_2>Постоянный</IP_ClientStatus_2>
        <IP_ClientDiscount>Скидка</IP_ClientDiscount>
        <IP_ClientIncorrectDiscountFormat>Неверный формат скидки!</IP_ClientIncorrectDiscountFormat>
        <IP_ClientAdd>Добавить клиента</IP_ClientAdd>
        <IP_ClientEdit>Редактировать клиента</IP_ClientEdit>
        <IP_OrderDate>Дата заказа</IP_OrderDate>
        <IP_OrderQuantity>Количество товара</IP_OrderQuantity>
        <IP_InvoicesID>Номер накладной</IP_InvoicesID>
        <IP_InvoicesOrdered>Заказано</IP_InvoicesOrdered>
        <IP_InvoicesReceived>Получено</IP_InvoicesReceived>
        <IP_InvoicesPrice>Цена</IP_InvoicesPrice>
        <IP_InvoicesPoints>Баллы</IP_InvoicesPoints>
        <IP_ProductID>Код продукта</IP_ProductID>
        <IP_ProductGetDate>Дата накладной</IP_ProductGetDate>
        <IP_ProductGetPrice>Цена накладной</IP_ProductGetPrice>
        <IP_ProductRealDate>Дата реализации</IP_ProductRealDate>
        <IP_ProductRealPrice>Цена реализации</IP_ProductRealPrice>
        <IP_EventsComing>Начало события</IP_EventsComing>
        <IP_EventsCompletion>Конец события</IP_EventsCompletion>
        <IP_EventsFixed>Завершено</IP_EventsFixed>
        <IP_EventInfo>Событие</IP_EventInfo>
	    <IP_Contact>Контакт</IP_Contact>
        <IP_ContactPhone>Телефон</IP_ContactPhone>
        <IP_ContactWhereFind>Как найден</IP_ContactWhereFind>
        <IP_ContactWhereFind_1>SMS-викторина</IP_ContactWhereFind_1>
        <IP_ContactWhereFind_2>Анкетирование</IP_ContactWhereFind_2>
        <IP_ContactWhereFind_3>Рекомендация</IP_ContactWhereFind_3>
        <IP_ContactWhereFind_4>Другое</IP_ContactWhereFind_4>
        <IP_ContactName>Имя</IP_ContactName>
        <IP_ContactDate>Дата</IP_ContactDate>
        <IP_ContactStatus>Состояние</IP_ContactStatus>
    </locallist>
</Localization>

=== kwoqer/ocons/ocons/db/lang_UA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Localization SYSTEM "local.dtd">
<Localization lang="">
    <locallist>
        <G_Language></G_Language>
        <G_Attention></G_Attention>
        <G_Error></G_Error>
        <G_Open></G_Open>
        <G_Save></G_Save>
        <G_Cancel></G_Cancel>
        <G_Yes></G_Yes>
        <G_No></G_No>
        <G_Ok></G_Ok>
        <G_AYouSure></G_AYouSure>
        <ACD_Title></ACD_Title>
        <ACD_PersonalNumber></ACD_PersonalNumber>
        <ACD_Name></ACD_Name>
        <ACD_Phone></ACD_Phone>
        <ACD_EMail></ACD_EMail>
        <ACD_Remember></ACD_Remember>
        <ACD_Password></ACD_Password>
        <ACD_RepeatPassword></ACD_RepeatPassword>
        <ACD_RedLighting></ACD_RedLighting>
        <ACD_ConsultantPresent></ACD_ConsultantPresent>
        <ACD_PasswordsNotCoincide></ACD_PasswordsNotCoincide>
        <LD_Title></LD_Title>
        <LD_Number></LD_Number>
        <LD_Password></LD_Password>
        <LD_Enter></LD_Enter>
        <LD_ConsultantNumberNotPoint></LD_ConsultantNumberNotPoint>
        <LD_IncorrectPassword></LD_IncorrectPassword>
        <LD_ConsultantNumberNotFound></LD_ConsultantNumberNotFound>
        <MM_1_Control></MM_1_Control>
        <MM_Config></MM_Config>
        <MM_AboutProgram></MM_AboutProgram>
        <MM_Exit></MM_Exit>
        <MM_2_Consultant></MM_2_Consultant>
        <MM_NewConsultant></MM_NewConsultant>
        <MM_Enter></MM_Enter>
        <MM_OtherConsultant></MM_OtherConsultant>
        <MM_ConfirmOtherConsultant></MM_ConfirmOtherConsultant>
        <NT_Clients></NT_Clients>
        <NT_Invoices></NT_Invoices>
        <NT_Catalogs></NT_Catalogs>
        <NT_Pricelist></NT_Pricelist>
        <NT_Reports></NT_Reports>
        <NT_Orders></NT_Orders>
        <NT_Contacts></NT_Contacts>
        <IP_Clients></IP_Clients>
        <IP_Catalogs></IP_Catalogs>
        <IP_Orders></IP_Orders>
        <IP_Invoices></IP_Invoices>
        <IP_Prices></IP_Prices>
        <IP_AddAction></IP_AddAction>
        <IP_DeleteAction></IP_DeleteAction>
        <IP_EditAction></IP_EditAction>
        <IP_FindAction></IP_FindAction>
        <IP_PreviewAction></IP_PreviewAction>
        <IP_PrintAction></IP_PrintAction>
        <IP_CatalogNumber></IP_CatalogNumber>
        <IP_CatalogGiveDate></IP_CatalogGiveDate>
        <IP_CatalogReturnDate></IP_CatalogReturnDate>
        <IP_CatalogReturned></IP_CatalogReturned>
        <IP_CatalogInfo></IP_CatalogInfo>
        <IP_ClientName></IP_ClientName>
        <IP_ClientPhone></IP_ClientPhone>
        <IP_ClientPhoneMob></IP_ClientPhoneMob>
        <IP_ClientAdress></IP_ClientAdress>
        <IP_ClientBirthday></IP_ClientBirthday>
        <IP_ClientOther></IP_ClientOther>
        <IP_ClientOtherDate></IP_ClientOtherDate>
        <IP_ClientStatus></IP_ClientStatus>
        <IP_ClientStatus_1></IP_ClientStatus_1>
        <IP_ClientStatus_2></IP_ClientStatus_2>
        <IP_ClientDiscount></IP_ClientDiscount>
        <IP_ClientIncorrectDiscountFormat></IP_ClientIncorrectDiscountFormat>
        <IP_ClientAdd></IP_ClientAdd>
        <IP_ClientEdit></IP_ClientEdit>
        <IP_OrderDate></IP_OrderDate>
        <IP_OrderQuantity></IP_OrderQuantity>
        <IP_InvoicesID></IP_InvoicesID>
        <IP_InvoicesOrdered></IP_InvoicesOrdered>
        <IP_InvoicesReceived></IP_InvoicesReceived>
        <IP_InvoicesPrice></IP_InvoicesPrice>
        <IP_InvoicesPoints></IP_InvoicesPoints>
        <IP_ProductID></IP_ProductID>
        <IP_ProductGetDate></IP_ProductGetDate>
        <IP_ProductGetPrice></IP_ProductGetPrice>
        <IP_ProductRealDate></IP_ProductRealDate>
        <IP_ProductRealPrice></IP_ProductRealPrice>
        <IP_EventsComing></IP_EventsComing>
        <IP_EventsCompletion></IP_EventsCompletion>
        <IP_EventsFixed></IP_EventsFixed>
        <IP_EventInfo></IP_EventInfo>
        <IP_ContactPhone></IP_ContactPhone>
        <IP_ContactWhereFind></IP_ContactWhereFind>
        <IP_ContactWhereFind_1></IP_ContactWhereFind_1>
        <IP_ContactWhereFind_2></IP_ContactWhereFind_2>
        <IP_ContactWhereFind_3></IP_ContactWhereFind_3>
        <IP_ContactWhereFind_4></IP_ContactWhereFind_4>
        <IP_ContactName></IP_ContactName>
        <IP_ContactDate></IP_ContactDate>
        <IP_ContactStatus></IP_ContactStatus>
        <IP_Contact></IP_Contact>
    </locallist>
</Localization>
