=== kwoqer/ocons/trunk/ocons/db/struct.dtd
<!ELEMENT DBStructure (database)>
<!ELEMENT database (databasename, tables)>
<!ELEMENT tables (table)+>
<!ELEMENT table (tablename, fields)>
<!ELEMENT fields (field)+>
<!ELEMENT field (fieldname, fieldtype)>
<!ELEMENT databasename (#PCDATA)>
<!ELEMENT tablename (#PCDATA)>
<!ELEMENT fieldname (#PCDATA)>
<!ELEMENT fieldtype (#PCDATA)>

=== kwoqer/ocons/trunk/ocons/db/ocons.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DBStructure SYSTEM "struct.dtd">
<DBStructure>
    <database>
        <databasename>ocons</databasename>
        <tables>
            <table>
                <tablename>PriceStore</tablename>
                <fields>
                    <field>
                        <fieldname>Cat_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>                        
                    </field>
                    <field>
                        <fieldname>Prod_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Name</fieldname>
                        <fieldtype>VARCHAR</fieldtype>
                        <fieldsize>50</fieldsize>
                    </field>
                    <field>
                        <fieldname>Price1</fieldname>
                        <fieldtype>NUMERIC</fieldtype>
                        <fieldsize>5,2</fieldsize>
                    </field>
                    <field>
                        <fieldname>Price2</fieldname>
                        <fieldtype>NUMERIC</fieldtype>
                        <fieldsize>5,2</fieldsize>
                    </field>
                    <field>
                        <fieldname>Price3</fieldname>
                        <fieldtype>NUMERIC</fieldtype>
                        <fieldsize>5,2</fieldsize>
                    </field>
                    <field>
                        <fieldname>Points</fieldname>
                        <fieldtype>NUMERIC</fieldtype>
                        <fieldsize>3</fieldsize>
                    </field>
                    <field>
                        <fieldname>CatPage</fieldname>
                        <fieldtype>NUMERIC</fieldtype>
                        <fieldsize>3</fieldsize>
                    </field>
                </fields>
            </table>
            <table>
                <tablename>Prices</tablename>
                <fields>
                    <field>
                        <fieldname>Prod_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                        <fieldkey>PRIMARY KEY</fieldkey>
                    </field>
                    <field>
                        <fieldname>Name</fieldname>
                        <fieldtype>VARCHAR</fieldtype>
                        <fieldsize>50</fieldsize>
                    </field>
                    <field>
                        <fieldname>Price1</fieldname>
                        <fieldtype>NUMERIC</fieldtype>
                        <fieldsize>5,2</fieldsize>
                    </field>
                    <field>
                        <fieldname>Price2</fieldname>
                        <fieldtype>NUMERIC</fieldtype>
                        <fieldsize>5,2</fieldsize>
                    </field>
                    <field>
                        <fieldname>Price3</fieldname>
                        <fieldtype>NUMERIC</fieldtype>
                        <fieldsize>5,2</fieldsize>
                    </field>
                    <field>
                        <fieldname>Points</fieldname>
                        <fieldtype>NUMERIC</fieldtype>
                        <fieldsize>3</fieldsize>
                    </field>
                    <field>
                        <fieldname>Cat_ID</fieldname>
                        <fieldtype>NUMERIC</fieldtype>
                        <fieldsize>6</fieldsize>
                    </field>
                    <field>
                        <fieldname>CatPage</fieldname>
                        <fieldtype>NUMERIC</fieldtype>
                        <fieldsize>3</fieldsize>
                    </field>
                    <field>
                        <fieldname>Special</fieldname>
                        <fieldtype>CHAR</fieldtype>
                        <fieldsize>1</fieldsize>
                    </field>
                </fields>
            </table>
            <table>
                <tablename>Conditions</tablename>
                <fields>
                    <field>
                        <fieldname>Cond_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                        <fieldkey>PRIMARY KEY AUTOINCREMENT</fieldkey>
                    </field>
                    <field>
                        <fieldname>CondType</fieldname>
                        <fieldtype>CHAR</fieldtype>
                        <fieldsize>1</fieldsize>
                    </field>
                    <field>
                        <fieldname>N</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>M</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>K</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Summa</fieldname>
                        <fieldtype>NUMERIC</fieldtype>
                        <fieldsize>5,2</fieldsize>
                    </field>
                </fields>
            </table>
            <table>
                <tablename>Groups</tablename>
                <fields>
                    <field>
                        <fieldname>Group_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                        <fieldkey>PRIMARY KEY</fieldkey>
                    </field>
                    <field>
                        <fieldname>Cond_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Name</fieldname>
                        <fieldtype>VARCHAR</fieldtype>
                        <fieldsize>15</fieldsize>
                    </field>
                </fields>
            </table>
            <table>
                <tablename>MGroup</tablename>
                <fields>
                    <field>
                        <fieldname>Group_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Cond_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Prod_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Price1</fieldname>
                        <fieldtype>NUMERIC</fieldtype>
                        <fieldsize>5,2</fieldsize>
                    </field>
                    <field>
                        <fieldname>Price2</fieldname>
                        <fieldtype>NUMERIC</fieldtype>
                        <fieldsize>5,2</fieldsize>
                    </field>
                    <field>
                        <fieldname>Price3</fieldname>
                        <fieldtype>NUMERIC</fieldtype>
                        <fieldsize>5,2</fieldsize>
                    </field>
                    <field>
                        <fieldname>Points</fieldname>
                        <fieldtype>NUMERIC</fieldtype>
                        <fieldsize>3</fieldsize>
                    </field>
                </fields>
            </table>
            <table>
                <tablename>KGroup</tablename>
                <fields>
                    <field>
                        <fieldname>Group_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Cond_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Prod_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Price1</fieldname>
                        <fieldtype>NUMERIC</fieldtype>
                        <fieldsize>5,2</fieldsize>
                    </field>
                    <field>
                        <fieldname>Price2</fieldname>
                        <fieldtype>NUMERIC</fieldtype>
                        <fieldsize>5,2</fieldsize>
                    </field>
                    <field>
                        <fieldname>Price3</fieldname>
                        <fieldtype>NUMERIC</fieldtype>
                        <fieldsize>5,2</fieldsize>
                    </field>
                    <field>
                        <fieldname>Points</fieldname>
                        <fieldtype>NUMERIC</fieldtype>
                        <fieldsize>3</fieldsize>
                    </field>
                </fields>
            </table>
            <table>
                <tablename>CatCalendar</tablename>
                <fields>
                    <field>
                        <fieldname>Cat_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                        <fieldkey>PRIMARY KEY</fieldkey>
                    </field>
                    <field>
                        <fieldname>CatBegin</fieldname>
                        <fieldtype>DATE</fieldtype>
                    </field>
                    <field>
                        <fieldname>CatEnd</fieldname>
                        <fieldtype>DATE</fieldtype>
                    </field>
