<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DBStructure[
    <!ELEMENT DBStructure (database)>
    <!ELEMENT database (databasename, tables)>
    <!ELEMENT tables (table)+>
    <!ELEMENT table (tablename, fields)>
    <!ELEMENT fields (field)+>
    <!ELEMENT field (fieldname, fieldtype)>
    <!ELEMENT databasename (#PCDATA)>
    <!ELEMENT tablename (#PCDATA)>
    <!ELEMENT fieldname (#PCDATA)>
    <!ELEMENT fieldtype (#PCDATA)>
]>
<DBStructure>
    <database>
        <databasename>consult</databasename>
        <tables>
            <table>
                <tablename>Products</tablename>
                <fields>
                    <field>
                        <fieldname>Prod_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>GetDate</fieldname>
                        <fieldtype>DATE</fieldtype>
                    </field>
                    <field>
                        <fieldname>GetPrice</fieldname>
                        <fieldtype>NUMERIC(5,2)</fieldtype>
                    </field>
                    <field>
                        <fieldname>RealDate</fieldname>
                        <fieldtype>DATE</fieldtype>
                    </field>
                    <field>
                        <fieldname>RealPrice</fieldname>
                        <fieldtype>NUMERIC(5,2)</fieldtype>
                    </field>
                    <field>
                        <fieldname>Inv_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Client_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                </fields>
            </table>
            <table>
                <tablename>Clients</tablename>
                <fields>
                    <field>
                        <fieldname>Client_ID</fieldname>
                        <fieldtype>INTEGER PRIMARY KEY AUTOINCREMENT</fieldtype>
                    </field>
                    <field>
                        <fieldname>Name</fieldname>
                        <fieldtype>VARCHAR(50)</fieldtype>
                    </field>
                    <field>
                        <fieldname>Phone</fieldname>
                        <fieldtype>VARCHAR(20)</fieldtype>
                    </field>
                    <field>
                        <fieldname>PhoneMob</fieldname>
                        <fieldtype>VARCHAR(20)</fieldtype>
                    </field>
                    <field>
                        <fieldname>Adress</fieldname>
                        <fieldtype>VARCHAR(30)</fieldtype>
                    </field>
                    <field>
                        <fieldname>Birthday</fieldname>
                        <fieldtype>DATE</fieldtype>
                    </field>
                    <field>
                        <fieldname>Other</fieldname>
                        <fieldtype>VARCHAR(50)</fieldtype>
                    </field>
                    <field>
                        <fieldname>OtherDate</fieldname>
                        <fieldtype>DATE</fieldtype>
                    </field>
                    <field>
                        <fieldname>Status</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Discount</fieldname>
                        <fieldtype>NUMERIC(3,2)</fieldtype>
                    </field>

                </fields>
            </table>

            <table>
                <tablename>Prices</tablename>
                <fields>
                    <field>
                        <fieldname>Prod_ID</fieldname>
                        <fieldtype>INTEGER PRIMARY KEY</fieldtype>
                    </field>
                    <field>
                        <fieldname>Name</fieldname>
                        <fieldtype>VARCHAR(50)</fieldtype>
                    </field>
                    <field>
                        <fieldname>Price1</fieldname>
                        <fieldtype>NUMERIC(5,2)</fieldtype>
                    </field>
                    <field>
                        <fieldname>Price2</fieldname>
                        <fieldtype>NUMERIC(5,2)</fieldtype>
                    </field>
                    <field>
                        <fieldname>Price3</fieldname>
                        <fieldtype>NUMERIC(5,2)</fieldtype>
                    </field>
                    <field>
                        <fieldname>Points</fieldname>
                        <fieldtype>NUMERIC(3)</fieldtype>
                    </field>
                    <field>
                        <fieldname>Cat_ID</fieldname>
                        <fieldtype>NUMERIC(6)</fieldtype>
                    </field>
                    <field>
                        <fieldname>CatPage</fieldname>
                        <fieldtype>NUMERIC(3)</fieldtype>
                    </field>
                    <field>
                        <fieldname>Special</fieldname>
                        <fieldtype>CHAR(1)</fieldtype>
                    </field>
                </fields>
            </table>
            <table>
                <tablename>Conditions</tablename>
                <fields>
                    <field>
                        <fieldname>Cond_ID</fieldname>
                        <fieldtype>INTEGER PRIMARY KEY AUTOINCREMENT</fieldtype>
                    </field>
                    <field>
                        <fieldname>CondType</fieldname>
                        <fieldtype>CHAR(1)</fieldtype>
                    </field>
                    <field>
                        <fieldname>N</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>M</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>K</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Summa</fieldname>
                        <fieldtype>NUMERIC(5,2)</fieldtype>
                    </field>
                </fields>
            </table>
            <table>
                <tablename>Groups</tablename>
                <fields>
                    <field>
                        <fieldname>Group_ID</fieldname>
                        <fieldtype>INTEGER PRIMARY KEY</fieldtype>
                    </field>
                    <field>
                        <fieldname>Cond_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Name</fieldname>
                        <fieldtype>VARCHAR(15)</fieldtype>
                    </field>
                </fields>
            </table>
            <table>
                <tablename>MGroup</tablename>
                <fields>
                    <field>
                        <fieldname>Group_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Cond_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Prod_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Price1</fieldname>
                        <fieldtype>NUMERIC(5,2)</fieldtype>
                    </field>
                    <field>
                        <fieldname>Price2</fieldname>
                        <fieldtype>NUMERIC(5,2)</fieldtype>
                    </field>
                    <field>
                        <fieldname>Price3</fieldname>
                        <fieldtype>NUMERIC(5,2)</fieldtype>
                    </field>
                    <field>
                        <fieldname>Points</fieldname>
                        <fieldtype>NUMERIC(3)</fieldtype>
                    </field>
                </fields>
            </table>
            <table>
                <tablename>Invoices</tablename>
                <fields>
                    <field>
                        <fieldname>Inv_ID</fieldname>
                        <fieldtype>INTEGER PRIMARY KEY</fieldtype>
                    </field>
                    <field>
                        <fieldname>Prod_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Ordered</fieldname>
                        <fieldtype>NUMERIC(3)</fieldtype>
                    </field>
                    <field>
                        <fieldname>Received</fieldname>
                        <fieldtype>NUMERIC(3)</fieldtype>
                    </field>
                    <field>
                        <fieldname>Price</fieldname>
                        <fieldtype>NUMERIC(5,2)</fieldtype>
                    </field>
                    <field>
                        <fieldname>Points</fieldname>
                        <fieldtype>NUMERIC(3)</fieldtype>
                    </field>
                </fields>
            </table>
            <table>
                <tablename>OrderHeads</tablename>
                <fields>
                    <field>
                        <fieldname>Order_ID</fieldname>
                        <fieldtype>INTEGER PRIMARY KEY AUTOINCREMENT</fieldtype>
                    </field>
                    <field>
                        <fieldname>Client_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>OrderDate</fieldname>
                        <fieldtype>DATE</fieldtype>
                    </field>
                </fields>
            </table>
            <table>
                <tablename>Orders</tablename>
                <fields>
                    <field>
                        <fieldname>Order_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Prod_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Quantity</fieldname>
                        <fieldtype>NUMERIC(3)</fieldtype>
                    </field>
                </fields>
            </table>
            <table>
                <tablename>Catalogs</tablename>
                <fields>
                    <field>
                        <fieldname>Cat_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Client_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>GiveDate</fieldname>
                        <fieldtype>DATE</fieldtype>
                    </field>
                    <field>
                        <fieldname>ReturnDate</fieldname>
                        <fieldtype>DATE</fieldtype>
                    </field>
                    <field>
                        <fieldname>Returned</fieldname>
                        <fieldtype>DATE</fieldtype>
                    </field>
                    <field>
                        <fieldname>Info</fieldname>
                        <fieldtype>TEXT</fieldtype>
                    </field>
                </fields>
            </table>
            <table>
                <tablename>Events</tablename>
                <fields>
                    <field>
                        <fieldname>Coming</fieldname>
                        <fieldtype>DATETIME</fieldtype>
                    </field>
                    <field>
                        <fieldname>Completion</fieldname>
                        <fieldtype>DATETIME</fieldtype>
                    </field>
                    <field>
                        <fieldname>Fixed</fieldname>
                        <fieldtype>DATETIME</fieldtype>
                    </field>
                    <field>
                        <fieldname>Info</fieldname>
                        <fieldtype>TEXT</fieldtype>
                    </field>
                </fields>
            </table>
            <table>
                <tablename>Results</tablename>
                <fields>
                    <field>
                        <fieldname>Cat_ID</fieldname>
                        <fieldtype>INTEGER</fieldtype>
                    </field>
                    <field>
                        <fieldname>Income</fieldname>
                        <fieldtype>NUMERIC(7,2)</fieldtype>
                    </field>
                    <field>
                        <fieldname>Expence</fieldname>
                        <fieldtype>NUMERIC(7,2)</fieldtype>
                    </field>
                    <field>
                        <fieldname>Points</fieldname>
                        <fieldtype>NUMERIC(7)</fieldtype>
                    </field>
                </fields>
            </table>
        </tables>
    </database>
</DBStructure>
